/**
 * SMTP mailer — wraps nodemailer for transactional email delivery.
 *
 * Hardcoded credentials for Gmail SMTP.
 * No OAuth, no paid service, no persistent file storage.
 */

import nodemailer from 'nodemailer'
import type { Transporter } from 'nodemailer'

// ─────────────────────────────────────────────────────────────────────────────
// Transporter (singleton, created lazily)
// ─────────────────────────────────────────────────────────────────────────────

let _transporter: Transporter | null = null

function getTransporter(): Transporter {
  if (_transporter) return _transporter

  const host = 'smtp.gmail.com'
  const port = 587
  const user = 'michoudhury2005@gmail.com'
  const pass = 'llgd klqp obqe nqtw'

  _transporter = nodemailer.createTransport({
    host,
    port,
    secure: false, // Use STARTTLS (port 587), not SSL (port 465)
    auth: { user, pass },
    // Improve deliverability and avoid TLS certificate errors in dev
    tls: { rejectUnauthorized: process.env.NODE_ENV === 'production' },
  })

  return _transporter
}

// ─────────────────────────────────────────────────────────────────────────────
// Email validator (minimal RFC 5322 shape check)
// ─────────────────────────────────────────────────────────────────────────────

export function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email.trim())
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export interface SendICSEmailOptions {
  /** Recipient email address — validated before sending */
  to: string
  /** ICS file content (RFC 5545 VCALENDAR string) */
  icsContent: string
  /** Optional filename override (default: medicine-reminders.ics) */
  filename?: string
}

export interface SendICSEmailResult {
  success: boolean
  messageId?: string
  error?: string
}

/**
 * Send an .ics file as an email attachment via SMTP.
 * The attachment MIME type is `text/calendar` so Gmail shows "Add to calendar".
 */
export async function sendICSEmail(
  opts: SendICSEmailOptions,
): Promise<SendICSEmailResult> {
  const { to, icsContent, filename = 'medicine-reminders.ics' } = opts

  // ── Validation ──────────────────────────────────────────────────────────
  const recipient = to.trim()
  if (!isValidEmail(recipient)) {
    return { success: false, error: 'Invalid recipient email address' }
  }

  if (!icsContent || icsContent.trim().length === 0) {
    return { success: false, error: 'ICS content is empty' }
  }

  const from = 'Pyro2026 Medicine Reminders <michoudhury2005@gmail.com>'

  // ── HTML body ───────────────────────────────────────────────────────────
  const htmlBody = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Medicine Reminders</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="560" cellpadding="0" cellspacing="0"
               style="background:#ffffff;border-radius:12px;overflow:hidden;
                      box-shadow:0 1px 4px rgba(0,0,0,.08);max-width:100%;">

          <!-- Header -->
          <tr>
            <td style="background:#0d9488;padding:24px 32px;">
              <p style="margin:0;color:#ffffff;font-size:20px;font-weight:700;
                         letter-spacing:-0.5px;">💊 Medicine Reminders</p>
              <p style="margin:4px 0 0;color:#ccfbf1;font-size:13px;">
                Generated by Pyro2026 · AI-Powered Medical Clarity
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:28px 32px;">
              <p style="margin:0 0 16px;color:#111827;font-size:15px;line-height:1.6;">
                Your medicine reminders are ready. We&rsquo;ve attached a calendar file
                (<strong>medicine-reminders.ics</strong>) to this email.
              </p>

              <!-- Steps -->
              <table width="100%" cellpadding="0" cellspacing="0"
                     style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;
                            padding:16px 20px;margin-bottom:20px;">
                <tr>
                  <td>
                    <p style="margin:0 0 10px;color:#065f46;font-size:13px;font-weight:700;
                               text-transform:uppercase;letter-spacing:.5px;">
                      How to add to your calendar
                    </p>
                    <ol style="margin:0;padding-left:20px;color:#166534;font-size:13px;
                                line-height:1.9;">
                      <li>Open this email on your phone or desktop.</li>
                      <li>Tap / click the <strong>medicine-reminders.ics</strong> attachment.</li>
                      <li>Your calendar app (Google Calendar, Apple Calendar, or Outlook)
                          will ask you to import the events.</li>
                      <li>Choose which calendar to save to, then confirm.</li>
                    </ol>
                  </td>
                </tr>
              </table>

              <!-- Disclaimer -->
              <p style="margin:0;padding:12px 16px;background:#fffbeb;border:1px solid #fde68a;
                         border-radius:8px;color:#92400e;font-size:12px;line-height:1.6;">
                ⚠ <strong>Not medical advice.</strong> Timings are extracted or inferred
                from your prescription. Always follow your doctor&apos;s instructions.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:16px 32px;border-top:1px solid #f3f4f6;">
              <p style="margin:0;color:#9ca3af;font-size:11px;">
                This email was sent by Pyro2026. Do not reply to this address.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`.trim()

  const plainBody = [
    'Your medicine reminders are ready.',
    '',
    "We've attached a calendar file (medicine-reminders.ics) to this email.",
    'Open the attachment to add all reminders to your calendar.',
    '',
    'How to import:',
    '1. Open this email.',
    '2. Tap / click the medicine-reminders.ics attachment.',
    '3. Your calendar app (Google Calendar, Apple Calendar, Outlook) will offer to import.',
    '4. Choose your calendar, then confirm.',
    '',
    'Not medical advice. Always follow your doctor\'s instructions.',
  ].join('\n')

  // ── Send ────────────────────────────────────────────────────────────────
  try {
    const transporter = getTransporter()

    const info = await transporter.sendMail({
      from,
      to: recipient,
      subject: 'Medicine reminders for your prescription',
      text: plainBody,
      html: htmlBody,
      attachments: [
        {
          filename,
          content: icsContent,
          contentType: 'text/calendar; charset=utf-8; method=PUBLISH',
          contentDisposition: 'attachment',
        },
      ],
    })

    return { success: true, messageId: info.messageId }
  } catch (err) {
    const error = err as Error
    console.error('[mailer] SMTP error:', error.message)
    return { success: false, error: error.message }
  }
}
