/**
 * ICS (iCalendar) generation utility.
 * Converts structured medicine schedule data → standards-compliant .ics content.
 * Pure client-side; no external API, no OAuth.
 */

export interface MedicineSchedule {
  /** Full medicine name with dosage, e.g. "Amoxicillin 500mg" */
  name: string
  /** Human-readable duration, e.g. "7 days" */
  duration: string
  /** Duration expressed as integer days (used for RRULE COUNT) */
  durationDays: number
  /** Human-readable frequency, e.g. "Twice daily" */
  frequency: string
  /**
   * Timings in 24-hour HH:MM format.
   * May be extracted from the prescription or inferred from frequency.
   * Empty array → medicine is not eligible for calendar export.
   */
  timings: string[]
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function pad(n: number): string {
  return n.toString().padStart(2, '0')
}

/** Format a Date as a local-time ICS datetime string (no UTC offset) */
function toICSDateTime(d: Date): string {
  return (
    d.getFullYear().toString() +
    pad(d.getMonth() + 1) +
    pad(d.getDate()) +
    'T' +
    pad(d.getHours()) +
    pad(d.getMinutes()) +
    '00'
  )
}

/** Escape special characters in ICS text fields */
function escapeICS(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n')
}

/** Fold long lines per RFC 5545 §3.1 (max 75 octets, continue with CRLF + space) */
function foldLine(line: string): string {
  if (line.length <= 75) return line
  const chunks: string[] = []
  chunks.push(line.slice(0, 75))
  let pos = 75
  while (pos < line.length) {
    chunks.push(' ' + line.slice(pos, pos + 74))
    pos += 74
  }
  return chunks.join('\r\n')
}

// ─────────────────────────────────────────────────────────────────────────────
// Core generator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate a complete iCalendar (.ics) string from an array of medicine schedules.
 *
 * @param medicines  Structured data from the AI prescription parser.
 * @param startDate  First day for events (defaults to today).
 * @returns          RFC 5545-compliant VCALENDAR string.
 */
export function generateICS(
  medicines: MedicineSchedule[],
  startDate: Date = new Date(),
): string {
  const now = Date.now()

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Pyro2026//Medicine Reminders//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:Medicine Reminders',
    'X-WR-CALDESC:Generated by Pyro2026 — medicine schedule from prescription',
  ]

  let eventCount = 0

  for (const med of medicines) {
    // Skip medicines with no timing information
    if (!med.timings || med.timings.length === 0) continue

    const count = Math.max(1, med.durationDays || 1)

    for (const timing of med.timings) {
      const [rawHours, rawMinutes] = timing.split(':').map(Number)
      if (isNaN(rawHours) || isNaN(rawMinutes)) continue

      // Build event start datetime
      const eventStart = new Date(
        startDate.getFullYear(),
        startDate.getMonth(),
        startDate.getDate(),
        rawHours,
        rawMinutes,
        0,
      )

      // If the time slot has already passed today, push to tomorrow
      if (eventStart.getTime() < Date.now()) {
        eventStart.setDate(eventStart.getDate() + 1)
      }

      const dtStart = toICSDateTime(eventStart)
      const slug = med.name.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()
      const uid = `med-${slug}-${rawHours}${pad(rawMinutes)}-${now + eventCount}@pyro2026`
      eventCount++

      const summary = `\uD83D\uDC8A Take ${med.name}`
      const description = escapeICS(
        `Take ${med.name}\nFrequency: ${med.frequency}\nDuration: ${med.duration}`,
      )

      lines.push(
        'BEGIN:VEVENT',
        foldLine(`UID:${uid}`),
        foldLine(`DTSTART:${dtStart}`),
        'DURATION:PT15M',
        `RRULE:FREQ=DAILY;COUNT=${count}`,
        foldLine(`SUMMARY:${escapeICS(summary)}`),
        foldLine(`DESCRIPTION:${description}`),
        // 5-minute reminder notification
        'BEGIN:VALARM',
        'TRIGGER:-PT5M',
        'ACTION:DISPLAY',
        foldLine(`DESCRIPTION:Reminder: Take ${escapeICS(med.name)}`),
        'END:VALARM',
        'END:VEVENT',
      )
    }
  }

  lines.push('END:VCALENDAR')

  // RFC 5545 §3.1 — lines MUST end with CRLF
  return lines.join('\r\n')
}

// ─────────────────────────────────────────────────────────────────────────────
// Download trigger (browser-only)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Trigger an .ics file download in the browser.
 * Uses a temporary object URL — no server required.
 */
export function downloadICS(
  medicines: MedicineSchedule[],
  filename = 'medicine-reminders.ics',
  startDate?: Date,
): void {
  const content = generateICS(medicines, startDate)
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  // Clean up after a brief delay
  setTimeout(() => URL.revokeObjectURL(url), 30_000)
}

/** Returns true if at least one medicine from the list has valid timings */
export function hasCalendarEligibleMedicines(medicines: MedicineSchedule[]): boolean {
  return medicines.some((m) => m.timings && m.timings.length > 0)
}
